
services:
  users:
    build: ./usuario_servico
    ports:
      - "8001:8000"
    networks:
      - marketplace

  products:
    build: ./produtos_servico
    ports:
      - "8002:8000"
    networks:
      - marketplace

  orders:
    build: ./pedidos_servico
    ports:
      - "8003:8000"
    networks:
      - marketplace
    depends_on:
      - users
      - products


networks:
  marketplace:
